from .model import load_ai_model

def detect_ai_content(text):
    """
    Analyzes the given text to determine if it was generated by an AI model.
    
    Args:
        text (str): Text to analyze.
    
    Returns:
        dict: Result of the analysis, including prediction of whether the text is AI-generated.
    """
    model = load_ai_model()
    result = model(text)
    print(f"AI Detection Result: {result}")
    return result

if __name__ == "__main__":
    sample_text = "This is an example of a text generated by AI."
    detect_ai_content(sample_text)
